efcsydney/efcsydney-roster

- api/controllers/events-controller.js
@Josephu this is a minor one, the contract the API returns is slightly different from the spec (the 'success' property is supposed to be named 'result').
> Api response format

- api/constants/datetime.js
- api/controllers/events-controller.js
- api/data/event-repository.js
- api/mapper/event-mapper.js
- api/models/calendar-date.js
- api/models/position.js
- api/service/events-service.js
- db/migrate/20171106121400-create-events.js
- db/migrate/20171107194226-create-position-table.js
- db/migrate/20171107194302-create-calendar-table.js
- db/seed/20171108052853-initialize-positions.js
- db/seed/20171217030641-fill-in-event-details.js
- test/helpers/test-helper.js
- test/integration-test/repository-test.js
- test/integration-test/server-test.js
- test/unit-test/event-mapper-test.js
- test/unit-test/event-service-test.js
這個PR做了幾個重要改動：
1. 資料表 calendarDate的資料結構 datetime -> date
2. 資料表 position增加欄位 order 來決定position的順序
我也把getEvent API中，所有的datetime object全部換成date string，所以程式碼簡化了很多。
另外在saveEvent API中，我移除了 addEvent，因為有pre-populate資料後，應該所有的 event 資料都會在。如果不在，需要raise error。
test和test data都有修改，讓他們能過。coverage跟以前一樣。
> Refactor quarterly query

- api/models/calendar-frequency.js
- api/models/frequency.js
- api/models/service.js
- api/utilities/datetime-util.js
- db/migrate/20180305094748-create-frequencies-table.js
- db/migrate/20180305095552-alter-service-table.js
- db/migrate/20180305125444-create-calendar-frequency-table.js
- db/migrate/20180316110622-alter-service-table.js
Create data migration that handles the new database schema changes to support different frequencies (Sunday, Saturday, Monthly) period
Additional Frequencies and CalendarDateFrequencies table are created to provide the required mapping between Service, Frequency and CalendarDates. The Frequency defines the frequency of a service, the CalendarDateFrequencies table maintains the actual mapping between the Frequency and its associated CalendarDates.
*
*
*
> Create migration for frequencies and calendare-frequencies

- client/src/modules/index/components/Container.js
- client/src/modules/index/components/EditRole.js
- client/src/modules/index/components/QuarterView/Desktop.js
- client/src/modules/index/components/QuarterView/InlineSelect.js
- client/src/modules/index/components/QuarterView/Mobile.js
- client/src/modules/index/components/QuarterView/index.js
- client/src/modules/index/redux.js
- client/src/modules/index/utils.js
As an user I would like to have a more efficient ways to enter specific role for different days so that I can finish my job more efficiently
From [Pongpong's recording](http://insights.hotjar.com/r?site=724853&recording=1147685846), we can see how difficult is for her to input. This ticket is focus on reducing the unnecessary clicking for assigning the user on the Desktop version.  
http://demo-roster.efcsydney.org
* Ensure you can click a name to see the dropdown list directly on the Desktop Quarter View.
* Ensure you can select a different person.
* Ensure the data is saved correctly. (You can reload the page to see if it works good.)
* Ensure the Mobile View still uses popup for editing and the saving still works good.
> Quarter View - Easier Input

- scripts/email/utils.js
On the Email, we don't show the service title. It's confusing when we have more services. 
> #216 Email - Add service caption

- api/service/send-email-service.js
Gary doesn't want to show the Sunday School services and Prayer Meeting on Email for now.
> #215 Email - Only showing Chinese and English services

- scripts/email/utils.js
On the E-mail, the table borders won't be `border-collapse: collapse` after being forwarded to others. Thus I changed the approach to show the borders. 
> #218 Email - Collapse the border

- api/service/send-email-service.js
- scripts/email/utils.js
Currently it shows 2px border. Better to remove it.
> #248 - Email tweaking again

- client/src/modules/index/components/Container.js
* Use the URL path first. If URL path is not available, use category from redux store.
* Correct the Component name. 
* Unlisten while the component is unmounted to avoid duplicate event handlings. 
Before QA, you can check the symptom on production first.
* Go to http://roster.efcsydney.org/#/english (`english` will be saved into cookies)
* Open a new browser tab
* Go to http://roster.efcsydney.org/#/admin/services
* **Manually** change the URL to http://roster.efcsydney.org/#/chinese
* It shows the English service incorrectly with the `/#/chinese` URL
* Go to http://demo-roster.efcsydney.org/#/english 
* Open a new browser tab
* Go to http://demo-roster.efcsydney.org/#/admin/services
* **Manually** change the URL to http://demo-roster.efcsydney.org/#/chinese
* Ensure it shows the …
> #228 - Showing incorrect service while updating URL manually from admin

- api/mapper/dto-mapper.js
- app.js
- test/helpers/test-helper.js
- test/integration-test/server-test.js
Create a new Service API to enable new service creation. 
The new end point is POST api/services
The sample data is listed below:
PLEASE NOTE: if the 'id' is supplied, it will 'Update' the service rather than 'Create'.
{
"name": "special-service2",
"locale": "zh-TW",
"label": "Special Service 2",
"footnoteLabel": "Visit",
"frequency": {"name": "Saturday"},
"positions": [
{"name": "Position 1", "order": "1"},
{"name": "Position 2", "order": "2"}
]
}
Use Postman
> #266: Create service API to enable service creation

- api/mapper/dto-mapper.js
- db/migrate/20180522113454-remove-position-unique-constraint.js
- test/integration-test/server-test.js
This change removes the unique constraint of service id and name fields in positions table. In addition, this ticket also addressed the data mapping issue. The PUT service was affected due to the change of data mapping rule.
https://demo-roster.efcsydney.org/admin
> added migration file to remove unique constraint

- client/src/resource/actions.js
Just provides a simple method to create multiple redux actions for API. 
```js
import { createApiActions } from 'resource/actions';
const actions = createApiActions('events');
console.log(actions);
//  output: 
{
createEvent,
createEventComplete,
createEventReset,
modifyEvent,
modifyEventComplete,
modifyEventReset,
destroyEvent,
destroyEventComplete,
destroyEventReset,
retrieveEvent,
retrieveEventComplete,
retrieveEventReset
}
```
> #284 Reusable API actions

- client/src/apis/index.js
- client/src/modules/core/components/NavBar.js
- client/src/modules/index/components/Container.js
- client/src/reducer.js
- client/src/resource/index.js
- client/src/resource/reducer.js
- client/src/resource/sagas.js
- client/src/sagas.js
Create and mount the reusable Sagas for the corresponded Redux API actions we created in #284 . When we dispatch any Redux API action, the `@resource` in the Redux store should get updated.
Sorry! It currently hasn't applied to any pages. You can only check the local state. 
http://localhost:3000/
I've dispatched `retrieveEvents` and `retrieveServices` from the following components.
* client/src/modules/index/components/Container.js
* client/src/modules/core/components/NavBar.js
> #294 Create reusable API sagas

- client/.babelrc
- client/config-overrides.js
- client/package.json
- client/src/components/Form.js
- client/src/components/index.js
- client/src/modules/admin/services/Popup.js
- client/yarn.lock
As an admin user
I would like to set a service URL path when I create a service
so that I can use this path name in my URL
http://demo-roster.efcsydney.org/#/admin/services/new
> #307 Service Admin > Create - Add URL Path select field

- client/src/modules/index/components/EditDay.js
Ability to customise the ${footnoteLabel} according to the Admin Service setting
https://demo-roster.efcsydney.org/#/english
https://demo-roster.efcsydney.org/#/admin/services/edit/1
> #243 Display the footnoteLabel

- api/controllers/events-controller.js
- api/controllers/services-controller.js
- client/package.json
- client/src/modules/index/components/Container.js
- client/src/modules/index/components/QuarterView/Mobile.js
- client/yarn.lock
As an user
I would like to access different quarter by entering the URL directly
so that I can make use of it for convenience such as saving as bookmarks
**Details**
* From Hotjar, we can see the user always have to switch manually to next quarter for entering new data for the next quarter. It's not very convenient for them.
* Currently we can't log different behaviours according to different URLs. It's a pity when we see the Hotjar heatmap.
**Spec**
* Default - `/index/:category`
* With specific date - `/index/:category?from=:from&to=:to`
https://demo-roster.efcsydney.org/#/index/chinese?from=2018-07-01&to=2018-09-30
> #141 Ability to use the URL to go to different quarter

- client/src/modules/index/redux.js
- client/src/modules/index/redux.test.js
1. Go to the Quarter View. Find a day which hasn't had any positions.
2. Specify a member to a role
3. Click the Day cell to edit the Footnote
4. Save the change
User can save it correctly without any JavaScript errors
https://demo-roster.efcsydney.org/#/index/english?from=2016-07-01&to=2016-09-30
> #331 Fix: Failed to edit the footnote in a specific condition

- .travis.yml
- docker/docker-compose.yml
This change is to tag every production service docker image with build number and source commit id
> add docker image tag on production

- client/src/modules/index/components/Container.js
- client/src/modules/index/components/EditDay.js
- client/src/modules/index/redux.js
- client/src/modules/index/redux.test.js
Currently the automatic updates is not working anymore. It's because we didn't  update the `setServiceInfo` and `setEvent` accordingly. 
https://demo-roster.efcsydney.org/#/index/english?from=2016-01-01&to=2016-03-31
1. Open the Quarter View 
1. Open the Quarter View in another tab. It can be another browser or even different devices, just make sure the URL is exactly the same with step 1. 
1. Update one of the cell, and check if another tab/browser/device is updated automatically.
1. Ensure another device is updated automatically.
> #335 Fix: Quarter View - Realtime updates not working anymore

- aws/ecs_service.json
Http to Https function. Now aws has supported the same function on Load balance. So we can remove redirect service.
es-support-for-redirects-and-fixed-responses-for-application-load-balancer/?nc1=h_ls
http://demo-roster.efcsydney.org/
> remove redirect service, using new ALB feature instead

- client/src/modules/admin/services/Popup.js
The position order is not working correctly. It's because the **ID wan't kept while user adjusted the order with drag-n-drop**. 
Besides, the replacement behaviour after the user drops a position item is not ordinary. It just swaps the position of dragging item and target item. Inserting the draggable item before the target item should be the expectable behaviour. 
https://demo-roster.efcsydney.org/#/admin/services/edit/1
> #420 Fix: Position not showing in correct order

- client/src/modules/admin/services/Popup.js
The position input is not working correctly after I implement the fix for #420. 
The default position item lacks of the `order` field. It causes problem while it sorts multiple fields with the order field.
https://demo-roster.efcsydney.org/#/admin/services/new
1. Go to Admin Services > Create dialog
1. Edit the first position
1. Create another position by clicking "Add New Position" link
1. Edit the new position by typing something 
Ensure the input should work correctly
> #425 Fix: Admin > Services > Create - Modifying positions not working properly

- client/package.json
- client/src/apis/index.js
- client/src/components/Form.js
- client/src/modules/admin/Container.js
- client/src/modules/admin/users/Container.js
- client/src/modules/admin/users/Popup.js
- client/src/modules/admin/users/index.js
- package.json
- yarn.lock
It's actually combine #361(list), #362(edit) and #411(create fake data, Kyle provide [it](https://drive.google.com/open?id=1tpZyvjRSzw1zUjyfnHhKEsySgEg723m9)).
Since I don't find an easy way to separate them without influence others.
Should be able to see user list, edit/create user.
Please checkout to #361 to test now since it should has some changes in the nearly future.
http://localhost:3000/#/admin/users
http://localhost:3000/#/admin/users/edit/1
http://localhost:3000/#/admin/users/create
> Add and Edit User

- client/src/components/Form.js
- client/src/components/index.js
- client/src/i18n.js
- client/src/modules/admin/services/Popup.js
- client/src/modules/index/components/EditDay.js
Now we can set `helpText` in the `<FormGroup/>` component.
https://demo-roster.efcsydney.org/#/admin/services/edit/1
> #445 UI Component > FormGroup - Add the helpText prop

- client/src/modules/index/components/EditRole.js
Fixing the issue we found in the pre-review meeting.
**QA Steps**
1. Go to the [QuarterView](https://demo-roster.efcsydney.org/#/index/english) and shrink the mobile resolution. 
1. Click any cell to specify someone to see the Edit Role dialog
1. Add someone who doesn't exist in the dropdown list (e.g. Julio Liang) and click the 'Create option "Julio Liang"'
Ensure the name you just typed in is shown in the box.
> #455 Quarter View on Mobile > Edit Role - Not showing the newly added person

- process.json
Just realised that the `ignore_watch` in `process.json` is not working so that PM2 also monitors the front-end files. I will use `watch` to specify the target folders instead.
You can only test this improvement ticket on your local machine.
> #466 Fix - PM2 watches too many unnecessary files
