client/package.json
client/src/components/QuarterView.js
client/src/icalstyle.css
client/src/utils.js
client/yarn.lock
package.json
yarn.lock

@josephj Please help to review, thanks.

Add icalendar

---

client/src/App.js
client/src/components/QuarterView.js
client/src/utils.js

@josephj @james1239090  Would it be better to show a loading icon in QuarterView before we got data from server?

Prevnext api integration

---

api/controllers/events-controller.js
api/infrastructure/sequelize-client.js
api/models/calendar.js
api/models/event.js
api/models/position.js
app.js
db/migrate/20171106121400-create-events.js
db/seed/20171108052853-initialize-positions.js
db/seed/20171111110130-initialize-calendars.js
db/seed/20171111110851-initialize-events.js

Kyle這只是個prototype，不過應該已經可以給你足夠的感覺了。
date這裡需要在處理，包括要改成between的query方式，以及要有辦法吃query string，這塊我想就麻煩你弄了。
在這個PR裡，我做了：
1. 三個table的seed資料，並且可以revert，因此測試可以用假資料，之後可以再透過undo處理掉：
seed: `./node_modules/.bin/sequelize db:seed:all`
undo: `./node_modules/.bin/sequelize db:seed:undo:all`
2. 我把所有的model name改成uppercase並用單數，因為model都是單一物件，而且class通常都是uppercase。
3. 我把timestamp設成true，我記得這個設定用了後，model會在save時自動提供createAt和updatedAt timestamp，所以你更新時，updatedAt都會透過sequelize更新。（不過我還沒測試，只是印象）
4. 我建了一個新的endpoint `/api/eventsfromdb`，讓我們可以先測試。

Build prototype of quarterly view

---

app.js
client/src/containers/App.js

@yhua045 please help to review.

implement save api

---

client/src/components/LoadingIndicator.js
client/src/containers/App.js

Just a loading indicator component when we need to have API call.

Add Loading Indicator

---

client/src/components/QuarterView.js

Simply remove other calendar from the menu.
Test heroku deployment

only support iCal & Google calendar

---

client/src/components/Modal.js
client/src/components/QuarterView.js
client/src/containers/Edit.js
client/src/index.css
client/src/styled.js

Added media query breakpoint (420px) for mobile devices.

Table - Responsiveness

---

README.md
api/controllers/events-controller.js
api/service/factory.js
client/src/api.js
client/src/containers/App.js

use test database in default:
http://localhost:3000/
If you want to use production database:
http://localhost:3000/?mock=false

Implement mock database switch for API

---

api/data/position-repository.js
test/integration-test/server-test.js

Reorder position for response.

Order position by ID

---

client/src/components/NavBar.js
client/src/components/QuarterView/Desktop.js
client/src/components/QuarterView/Mobile.js
client/src/components/QuarterView/index.js
client/src/components/QuarterView/styled.js
client/src/styled.js
client/src/utils.js

Refactoring to make CSS easier to understand

Separate Mobile & Desktop views

---

client/src/containers/App.js

Nowadays it's easier to make alignment or layout with CSS Flexbox. IE11 works good.
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

Fix - Arrow alignment

---

db/seed/20171111110130-initialize-calendars.js
db/seed/20171111110851-initialize-events.js

**Test Case**
1. `./node_modules/.bin/sequelize db:seed:undo:all`
1. `yarn db-seed`
1. Open browser to browse the previous quarter and next quater
Ensure you can see complete data for the previous quarter and incomplete data for the next quarter.

Add more sample data for demo

---

client/src/components/NavBar.js
client/src/components/QuarterView/styled.js
client/src/containers/App.js

@josephj  more space at bottom

Bugfix frontend last row missing

---

client/package.json
client/src/components/DateBar.js
client/src/components/NavBar.js
client/src/components/QuarterView/index.js
client/src/containers/App.js
client/src/index.css
client/src/utils.js
client/yarn.lock

* Refactored the prev/next arrows which uses a lot of `position:absolute`
* Will update URL and state for James to have further implementation

Header dropdown

---

README.md
api/controllers/events-controller.js
db/migrate/20171106121400-create-events.js
db/migrate/20171107194226-create-position-table.js
db/migrate/20171107194302-create-calendar-table.js
db/seed/20171108052853-initialize-positions.js
db/seed/20171111110130-initialize-calendars.js
db/seed/20171111110851-initialize-events.js
package.json
scripts/create-database.js
server.js
test/helpers/test-helper.js
test/integration-test/repository-test.js
test/integration-test/server-test.js
test/mocha.opts
yarn.lock

I have included the database cleaner, so now database will be cleaned in every test.
To make old tests pass, I have made a general seeding function to build similar data structure as before. But we should try to make custom data in the future and prevent utilizing this seeding function.
I also included `winston`, which is a logging tool. It is a bad practice to include `console.log` in the code base, so this will provide better logs as time goes on.
I have also added default time to NOW for `createdAt` and `updatedAt`, and clean up the seeding data.
**A note to this change is that, you will need to rollback all migrations and rerun them. I will inform the team to do it once this is merged.**

Add backend utilities

---

api/data/service-calendar-date-repository.js
api/models/service-calendar-date.js
test/helpers/test-helper.js
test/integration-test/repository-test.js
test/integration-test/server-test.js

Fixed the typo of ServiceCalendarDate

Change the timeout value to 5 seconds.

---

client/src/modules/index/components/QuarterView/Desktop.js

I use different solution :
if cells value are all the same in a row, make them looks like merged.
Pros : User can still click/edit each individual cell
Cons : it is a css trick, nothing merged.
Already committed to QA branch, I hope Travis will auto deploy it
@josephj  please help to review.

make cells look like merged if they are all same value in a row

---

api/service/send-email-service.js
deploy.sh
test/unit-test/send-email-service-test.js

@josephj 我把empty email list也做出來了，你用這個list就可以作UI了

Show empty email list

---

api/controllers/events-controller.js
api/controllers/service-info-controller.js
api/data/service-calendar-date-repository.js
api/mapper/dto-mapper.js
api/service/events-service.js
api/service/service-info-service.js
test/integration-test/server-test.js

The API hat supports PUT method needs to include items that have been updated as part of its response

Api include updated item in response

---

.travis.yml
api/controllers/events-controller.js
api/controllers/service-info-controller.js
api/utilities/pusher.js
client/package.json
client/src/config/pusher.json
client/src/modules/index/components/Container.js
client/src/modules/index/redux.js
client/src/utils/pusher.js
client/yarn.lock
config/default.yaml
config/production.yaml
config/qa.yaml
package.json
yarn.lock

Pusher - Integration

---

api/models/email-list-item.js
api/service/send-email-service.js

This will provide only the email list that is in the roster.
Tested on QA passed.

Filter email list for reminder

---

api/service/send-email-service.js
config/default.yaml
scripts/email/utils.js
test/unit-test/send-email-service-test.js

@Josephu 
I got 2 major issues for this one.
1. This should be implemented from the backend perspective, or it still sends emails to the people I hide. Can you help me to implement that part? Or guide me to do that?
1. I combined some fields by checking the duplication. However, the UI can fail when they are not connect to each other. Can we guarantee that?

Email - Exclude some positions from showing

---

api/controllers/services-controller.js
api/controllers/services-mock.json
app.js
client/src/App.js
client/src/apis/services.js
client/src/components/Button.js
client/src/components/Grid.js
client/src/components/index.js
client/src/index.css
client/src/modules/admin/Edit.js
client/src/modules/admin/index.js
package.json
yarn.lock

Created the listing UI for user to browse all existing services.
* Added `service-mock.json` for fake data
* Added the API entry point for `/api/services`
* Added the reusable `Button` component
* Make the Grid related component being reusable

Admin listing

---

client/src/components/Form.js
client/src/components/index.js
client/src/modules/admin/Edit.js
client/src/modules/admin/index.js
client/src/modules/index/components/EditDay.js

Ability to change the Service Title.
https://demo-roster.efcsydney.org/#/admin
* Added an input for user to change the Service Title
* Move the `<Input/>` to `components` folder for reusability
* Added the `onSave` callback for saving

Service title

---

api/controllers/services-controller.js
api/data/service-repository.js
api/mapper/dto-mapper.js
api/models/calendar-frequency.js
api/models/frequency.js
api/models/position.js
api/models/service.js
api/service/services-service.js
api/utilities/datetime-util.js
app.js
db/migrate/20180305094748-create-frequencies-table.js
db/migrate/20180305095552-alter-service-table.js
db/migrate/20180305125444-create-calendar-frequency-table.js

Create new api endpoint for returning the list of services and its associated information.
Create a new Frequency model and update Service model's association with Frequency and Position model

171 2 api get services

---

client/src/modules/admin/Edit.js

add frequency droplist 
- [ x ] Deployed to QA env successfully
- [ x ] Tested the feature on QA env with the expected behaviours

add frequency droplist

---

client/src/modules/admin/Edit.js

An editable list for admin to update the position name and ordering
* Ability to add new position
* Ability to delete position which is newly created
* Ability to modify existing positions
* Use local setstate

Admin edit positions

---

aws/README.md
aws/ec2.json
aws/vpc.yml

move infrastructure repo into roster

move infrastructure repo into roster

---

aws/ec2.json
aws/elb.json
aws/userdata

Add ELB for https request and add certificate on ELB
_Changes proposed in this pull request_
* Add ELB
* Move userdata from old repo

ELB cloudformation

---

client/src/modules/login/index.js

Added UI logic to handle login error response from Auth component
* Added loginError state to Login component
* Added renderLoginError method to update the login state
* Updated the render logic so it displays the login error message when 'no-permission' message is returned form Auth component

Admin > Login - Error Page

---

client/src/apis/services.js
client/src/modules/admin/index.js

As an user,
I would like to save the modified data into the database
so that my change can take effect.
* Save the database with `PUT /api/services/:id` API

Admin > Edit - Integration with Save API

---

client/src/modules/admin/Edit.js

Update the selection of Frequency on Admin Category
_Changes proposed in this pull request_
*
*
*

Update the selection of Frequency on Admin Category

---

api/middleware/http-redirect.js
app.js
config/default.yaml
server.js

Force redirect from HTTP to HTTPS
*Added HttpRedirect middleware
*Include the HttpRedirect in the request pipeline in production/qa environment
*Config the server so it listens to both secure and non-secure connection

Https redirect

---

client/src/modules/login/index.js

* Adjust error string's line-height 
* Adjust button's color on Login view

Adjust error string's line-height and button's color on Login view

---

config/database.json
deploy.sh

get database access data from AWS parameter store then save as database config json, during deployment
_Changes proposed in this pull request_
* get database access data from AWS parameter store then save as database config json
* remove sensitive database connection info
*

Database password protection

---

client/package.json
client/src/App.js
client/src/modules/admin/Edit.js
client/src/modules/core/components/NavBar.js
client/src/modules/core/redux.js
client/src/modules/core/sagas.js
client/src/modules/core/utils.js
client/src/modules/index/components/Container.js
client/src/modules/index/components/QuarterView/Desktop.js
client/src/modules/index/components/QuarterView/Mobile.js
client/src/modules/index/components/QuarterView/utils.js
client/src/sagas.js
client/src/store.js
client/src/utils.js
client/yarn.lock

Integrating new services into the Quarterly View
* Ensure you can switch to different services by using the NavBar dropdown
* Ensure you can switch to different services by inputting the URLs directing
* https://demo-roster.efcsydney.org/#/chinese
* https://demo-roster.efcsydney.org/#/english
* https://demo-roster.efcsydney.org/#/preschool-junior
* https://demo-roster.efcsydney.org/#/preschool-middle
* https://demo-roster.efcsydney.org/#/preschool-senior
* https://demo-roster.efcsydney.org/#/prayer
* Ensure the translation, label of footnote, and highlight does show correctly according to the settings in Admin portal

Frontend integration

---

api/utilities/database-util.js

Backup file rotation for 30 days

Backup file rotation for 30 days

---

.gitignore
api/controllers/email-controller.js
api/service/send-email-service.js
app.js
scripts/email/test/generate.js
scripts/email/test/mock-data.js

As a developer I would like to have an easier way to update the E-mail implementation so that we can be more efficient on email development.
Email development is quite inconvenient. We have to update the cron schedule and wait to receive the email. Thus I decide to make an URL which is dedicate for seeing Email template. 

#219 Email - Easier way for development

---

client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Popup.js

https://github.com/efcsydney/efcsydney-roster/issues/224
https://demo-roster.efcsydney.org/#/admin/services/edit/3

Footnote label changes to Description Label

---

client/src/modules/admin/services/Container.js

Remove the Description Label column

Admin > Service Index - Remove the Description Label

---

db/migrate/20180506160232-alter-frequencies-table.js

Added Everyday, Friday, Thursday, Wednesday, Tuesday, and Monday into db.
Original data doesn't be changed.
result:
+----+-----------+---------------------+---------------------+
| id | name      | createdAt           | updatedAt           |
+----+-----------+---------------------+---------------------+
|  1 | Sunday    | 2018-05-06 06:20:58 | 2018-05-06 06:20:58 |
|  2 | Saturday  | 2018-05-06 06:20:58 | 2018-05-06 06:20:58 |
|  3 | Month     | 2018-05-06 06:20:58 | 2018-05-06 06:20:58 |
|  4 | Friday    | 2018-05-06 06:24:09 | 2018-05-06 06:24:09 |
|  5 | Thursday  | 2018-05-06 06:24:09 | 2018-05-06 06:24:09 |
|  6 | Wednesday | 2018-05-06 06:24:09 | 2018-05-06 06:24:09 |
|  7 | Tuesday   | 2018-05-06 06:24:09 | 2018-05-06 06:24:09 |
|  8 | Monday    | 2018-05-06 06:24:09 | 2018-05-06 …

#245 - Update Frequency data

---

client/src/modules/index/components/QuarterView/Desktop.js
client/src/modules/index/components/QuarterView/Mobile.js

Grab roles title data from service API

#250 - Generate table of roles title column using service API 

---

client/src/modules/admin/services/Popup.js

Disable SAVE button when Service Title or Description Label is empty.
https://demo-roster.efcsydney.org/#/admin/services/new

#236: Ensure that the Service Title, Note Label are mandatory.

---

Entrypoint.sh
config/database.json
docker-compose.yml

Add default database setting for 'docker' environment to database.json

add database setting for 'docker' environment to database.json

---

api/controllers/email-controller.js
api/controllers/events-controller.js
api/controllers/service-info-controller.js
api/controllers/services-controller.js
api/service/events-service.js
api/utilities/logger.js
deploy.sh
scripts/create-database.js

As a developer I would like to have standard log with proper tag to speed up.
so that when issue happens, developers can check log faster.
Non. 
```
{"category":"english","from":"2018-04-01","to":"2018-06-30","level":"info","message":"getEvent","timestamp":"2018-05-26T05:38:51.956Z"}
{"category":"english","from":"2018-01-01","to":"2018-03-30","level":"info","message":"getEvent","timestamp":"2018-05-26T05:38:51.956Z"}
{"level":"info","message":"[BEGIN] DatabaseUtil#backupDatabase; file: efcRosterQa_20180527.sql, at: Sun May 27 2018 00:00:00 GMT+1000","timestamp":"2018-05-26T14:00:00.850Z"}
{"level":"info","message":"[END] DatabaseUtil#backupDatabase; Remove file: efcRosterQa_20180427.sql, at: Sun May 27 2018 00:00:00 GMT+1000","timestamp":"2018-05-26T14:00:00.893Z"} …
```

#271 log standardize 

---

client/package.json
client/src/apis/index.js
client/src/reducer.js
client/src/resource/reducer.js
client/src/resource/utils.js
client/yarn.lock

Add a root reducer which handles the API actions
https://demo-roster.efcsydney.org

#292 Create reusable API reducer

---

client/src/components/ExternalLink.js
client/src/components/index.js
client/src/modules/admin/services/Container.js

As a user, I can open a new tab, link to each service by click service’s name

#241 Link the title of each service to the service

---

client/src/apis/utils.js
client/src/components/StateButton.js
client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Popup.js
client/src/modules/core/components/NavBar.js
client/src/modules/index/components/QuarterView/Desktop.js
client/src/modules/index/redux.js
client/src/reducer.js
client/src/resource/connect.js
client/src/resource/index.js
client/src/resource/reducer.js
client/src/resource/sagas.js
yarn.lock

Add a `withResource` HoC so that we can fetch API data without manually dispatching action creator.
Simple
```js
withResource('events')(
class Container extends Component {
render() {
const { events } = this.props;
}
}
);
```
Advanced
```js
const mapStateToQuery = state => {
return {
...state['index'].query
};
});
const mapResourceToProps = (resource, otherState, ownProps) => {
data: resource.data,
...state['index']
};
withResource('events', mapResourceToProps, mapStateToQuery)(
class Container extends Component {
render() {
const { data } = this.props;
}
}
);
```

#297 withResource HoC

---

client/src/modules/admin/services/Popup.js

Disable SAVE button when the role field is empty.
https://demo-roster.efcsydney.org/#/admin/services/new ("Add Position" Not ready)
Use EDIT service to check:
https://demo-roster.efcsydney.org/#/admin/services/edit

#238: User can delete an existing role on Create services

---

client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Popup.js
client/src/resource/reducer.js

As a developer I need to know the action has been done correctly on the database
- Used the new UI (#307) and new way to handle submission.
- Fixed the issue with not able to get correct status for creating a service.  (no id while creating a service)

#235 API integration

---

client/src/modules/core/sagas.js

As an user
I would like to see the date in a correct format
so that I can easily figure out which day is it.
Currently the format is incorrect in all different places. (`01 4月, 2018`)

#322 Fix: Date format not showing correctly

---

client/src/modules/index/components/QuarterView/index.js

#316 Fix: getBoundingClientRect error

---

aws/elb.json

Tell reviewer something about this change 

Enable port 8080

---

.travis.yml
client/package.json
docker/docker-compose.yml

Tell reviewer something about this change 

Build docker image via travis#260

---

client/src/resource/actions.test.js
client/src/resource/reducer.js
client/src/resource/reducer.test.js

Adding automated tests for the resource library. Minor tweaks for current library code so that we can test it.

#315 Automated tests for resource library

---

aws/ecs_alb.json
aws/ecs_service.json

Enable Docker service on AWS ECS
https://demo-roster.efcsydney.org/

ECS Cloudformation

---

.travis.yml
docker_deploy.sh

Let Travis deploy ecs docker service with aws secret.
https://demo-roster.efcsydney.org/

travis-deploy docker service

---

test/e2e-test/index.fixture.js

User Story
As a developer, I would like to have E2E test on footnote update on mobile (just resize the browser to make the system behave like mobile)
Acceptance Criteria

Test Footnote on mobile

---

client/package.json
client/wallaby.js
client/yarn.lock

As a developer
I would like to **use tools which can help me to write unit/integration test easier**
so that **writing tests will be more efficient and fun**.
1. Install the Wallaby.js in you VSCode Editor.
2. Switch to `qa` branch.
3. Open a JS file which has a test. (e.g. `client/src/components/SwitchButton.test.js` and `client/src/components/SwitchButton.js`)
4. Start Wallaby.js by clicking `Cmd + Shift + P` and searching "Wallaby > Start"
5. It will ask you which configuration file you want to use. Just select the `wallaby.js`. 
6. Ensure you can see the green boxes for lines which has test covered.

#371 Evaluate Wallaby.js

---

docker/Dockerfile-dev
docker/Dockerfile-prod

Downgrade npm to version  npm@5.6.0 to fix this issue.

Fix install pm2 fail when building docker image

---

client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Nav.js

Tell reviewer something about this change 

#417 AdminNav

---

client/src/App.js
client/src/components/Form.js
client/src/components/Grid.js
client/src/modules/admin/Container.js
client/src/modules/admin/UnderConstruction.js
client/src/modules/admin/index.js
client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Nav.js

* Update the Admin Navigation
* Making the Admin Layout and refactoring the`<Route/>` 
* Responsive Enhancement
* Making scrollable Table 
* Vertical form label and control
https://demo-roster.efcsydney.org/#/admin
Our original plan is to have Users, the Email and Changelog are what I want to achieve. I will remove it if it's not doable.

#423 Admin Navigation enhancement and better mobile view

---

client/src/apis/utils.js
client/src/modules/admin/services/Container.js
client/src/resource/actions.js
client/src/resource/reducer.js
client/src/resource/sagas.js

1. Go to the [Admin Service > Create popup](https://demo-roster.efcsydney.org/#/admin/services/new) 
1. Fill up all the required fields. For the **URL Path** field, please provide a duplicate URL (e.g. `english`)
1. Click Save 
1. Ensure that you can see an error prompt which tells you the URL is duplicate
https://demo-roster.efcsydney.org/#/admin/services/new

#429 Fix: Admin Service > Create - Error Handling & Validation

---

test/e2e-test/index.fixture.js

E2E test - Change Month
https://demo-roster.efcsydney.org/

(0.5) #368 - E2E test - Change Month [0.5]

---

api/service/send-email-service.js
app.js
client/src/components/Grid.js
client/src/index.css
client/src/modules/admin/Container.js
client/src/modules/admin/Title.js
client/src/modules/admin/email/Container.js
client/src/modules/admin/email/index.js
client/src/modules/admin/services/Container.js
client/src/modules/admin/services/Nav.js
client/src/modules/core/components/Auth.js
client/src/modules/core/components/NavBar.js
scripts/email/utils.js

Add an admin page which allows user to see the email for upcoming 2 weeks anytime.
https://demo-roster.efcsydney.org/#/admin/email

#432 Admin > Email - Preview

---

docker/Entrypoint.sh

Update docker/Entrypoint.sh, Move `yarn db:migrate` after getting all files from S3
https://demo-roster.efcsydney.org/

move `yarn db:migrate` after getting all files from S3

---

client/src/components/Form.js
client/src/modules/admin/services/Popup.js
client/src/modules/admin/users/Popup.js
client/src/modules/index/components/Container.js

**Quarter View - Non-existing URL should be redirected**
@ryrocks 
It now redirects to the default English service.
https://demo-roster.efcsydney.org/#/index/english 
**HelpText adjustment**
@BearZi  https://demo-roster.efcsydney.org/#/admin/services/edit/1

#451 UI tweaks for the pre-review feedbacks

---

.travis.yml
test/e2e-test/index.fixture.js

Making use of the Travis Cron Job.  While it's a cron job build, the E2E test will be executed without deployment. 
https://travis-ci.org/efcsydney/efcsydney-roster/builds/430894681

#391 E2E Testing - Integrate with Travis

---

client/.babelrc
client/config-overrides.js
client/package-lock.json
client/package.json
client/src/index.ts
client/src/index.tsx
client/src/modules/index/components/QuarterView/Desktop.js
client/tsconfig.json
client/wallaby.js
client/yarn.lock
package.json
yarn.lock

TypeScript is a superset of JavaScript. It means our current JavaScript is already TypeScript. It's good for us to start using industrial best practice. 
This branch is based on #459

#464 Frontend - Ability to write TypeScript

---

package.json

Fixed by increasing from 1s to 10s.

#468 Fix: Travis build tests keep failing
